[package]
name = "Doice"
version = "0.1.1"
authors = ["Marijn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
console = "0.14.0"
dialoguer = "0.7.1"