[package]
name = "Doice"
version = "0.2.0"
authors = ["Marijn Buitenweg"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
console = "0.14.1"
dialoguer = "0.8.0"