/// Character manager
mod character_manager;
/// New dice roller
mod dice_roller;
/// Some testing stuff
mod dicerollpreset_gui_test;
/// Analyzes dicerolls generated by other activities
mod global_analyzer;
/// Basic dice roller activity based on the old TUI backend
mod legacy_dice_roller;
/// Notes
mod notes;
/// Allows the user to browse the list of spells with a basic search
mod spell_browser;
/// Starfury bombarder
mod starfury;

pub use character_manager::CharacterManager;
pub use dice_roller::DiceRoller;
pub use dicerollpreset_gui_test::DiceRollPresets;
pub use doice_gui::*;
pub use egui;
pub use global_analyzer::GlobalAnalyzer;
pub use legacy_dice_roller::LegacyDiceRoller;
pub use notes::Notes;
pub use spell_browser::SpellBrowser;
pub use starfury::StarfuryYeeter;
