[package]
name = "doice_os"
version = "0.2.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
doice_lib = { version = "0.1.0", path = "../../doice_lib", features = ["eframe", "rayon", "include_data"] }
clap = { version = "4.2.1", features = ["derive"] }